# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Published title')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('image_240x135', models.URLField(verbose_name='Image 240x135')),
                ('image_480x270', models.URLField(verbose_name='Image 480x270')),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ['-pk'],
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
