# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='identifier',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID'),
        ),
    ]
